version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: "npm install"
      - save_cache:
          key: "npm_packages"
          paths:
            - /src/node_modules 
      - run: "npm run lint"
      - run:
          command: "echo error occured"
          when: on_fail
  
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key: "npm_packages"
      - run: "npm i"
      - run: "npm test"
      - run:
          command: "echo error occured"
          when: on_fail
  
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key: "npm_packages"
      - run: "npm i"
      - run: "npm audit"
      - run:
          command: "echo error occured"
          when: on_fail


workflows:
  build-analyze:
    jobs:
      - build
      - test:
          requires:
            - "build"
      - analyze:
          requires:
            - "test"
  